-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 11:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homeinventorydb` ;

-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeinventorydb` DEFAULT CHARACTER SET latin1 ;
USE `homeinventorydb` ;

-- -----------------------------------------------------
-- Table `UserDatabase`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`roles` (
  `role_id` INT(11) NOT NULL,
  `role_name` VARCHAR(25) NOT NULL,
  `can_manage` BIT NOT NULL,
  PRIMARY KEY (`role_id`));

-- -----------------------------------------------------
-- Table `homeinventorydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`users` (
  `Username` VARCHAR(256) NOT NULL,
  `Password` VARCHAR(256) NOT NULL,
  `Email` VARCHAR(256) NOT NULL,
  `FirstName` VARCHAR(256) NOT NULL,
  `LastName` VARCHAR(256) NOT NULL,
  `Active` BIT NOT NULL,
  `Role` INT NOT NULL,
  PRIMARY KEY (`Username`),
CONSTRAINT `fk_user_role`
    FOREIGN KEY (`Role`)
    REFERENCES `homeinventorydb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `homeinventorydb`.`UUID_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`uuid_map` (
  `ID` int not null auto_increment,
  `Username` VARCHAR(256) NOT NULL,
  `Iterations` INT NOT NULL,
  `Salt` VARCHAR(32) NOT NULL,
  `UUID` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID`),
CONSTRAINT `fk_uuid_username`
    FOREIGN KEY (`Username`)
    REFERENCES `homeinventorydb`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `homeinventorydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`categories` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `homeinventorydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`items` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `Category` INT NOT NULL,
  `ItemName` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Owner` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `fk_items_Categories_idx` (`Category` ASC),
  INDEX `fk_items_users1_idx` (`Owner` ASC),
  CONSTRAINT `fk_items_Categories`
    FOREIGN KEY (`Category`)
    REFERENCES `homeinventorydb`.`categories` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`Owner`)
    REFERENCES `homeinventorydb`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
--
--

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `categories` (`CategoryName`) VALUES ('Kitchen');
INSERT INTO `categories` (`CategoryName`) VALUES ('Bathroom');
INSERT INTO `categories` (`CategoryName`) VALUES ('Living Room');
INSERT INTO `categories` (`CategoryName`) VALUES ('Basement');
INSERT INTO `categories` (`CategoryName`) VALUES ('Bedrooom');
INSERT INTO `categories` (`CategoryName`) VALUES ('Garage');
INSERT INTO `categories` (`CategoryName`) VALUES ('Office');
INSERT INTO `categories` (`CategoryName`) VALUES ('Utility room');
INSERT INTO `categories` (`CategoryName`) VALUES ('Storage');
INSERT INTO `categories` (`CategoryName`) VALUES ('Other');

INSERT INTO `roles` VALUES (1, 'System Administrator', 1);
INSERT INTO `roles` VALUES (2, 'Regular User', 0);

INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`) VALUES ('admin','10000:74e5a4fc99884c9bf94d7c1b645755d5:894ec6bdce764915f3d1c41c4a1d7084a8505a1c2bef53155f5566c743a58fc5c66dbab0d10428cd0f8e7420da3b990f644b9cbeca09f90181f2efa69285aa15','cprg352+admin@gmail.com','Admin','Admin',1,1);
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`) VALUES ('admin2','10000:fc234b5ca47e5d75553a5c96e7004f05:f036789a919d89177896faa3c473d878df7b008d38c285cbbc856f20b1011571f22612dd073cce2eb117f432cc870c577ffc9de59fe1b02b3d5a9170cf820e2c','cprg352+admin2@gmail.com','Admin2','Admin2',0,1);
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`) VALUES ('anne','10000:0cea7ec220f8d459c26a19601cadd2fa:1f96cf71d0f48793e1aaa6f2361ffdec1448d92414e725ed57f43bcc12accd0c760181b3b4674ecc094009c28e020b447658f3734b10a5c469086007de264c55','cprg352+anne@gmail.com','Anne','Annerson',1,2);
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`) VALUES ('barb','10000:9d593492b0f4d74bc4f48640fa08d01d:b8eb022ee17a9219edcfba483a121b76dade030eeb311bab167a7be08110c6a52148a324aae84cece702c982ea0c7bd1bbcdc2ba5ee42615e6c6d32c7bd4f71d','cprg352+barb@gmail.com','Barb','Barber',0,2);

INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`) VALUES ('tester','10000:48ea2eac4ed649c4867e17e29da5b317:43e963a8b2219c0e3f6df01d468b47db58b679ece2e16369aeee522b04a40d3df36d5118a61a123481d269ebff7321237e76666898824fc539f2a6a29095408f','WebDev352+tester@gmail.com','Forgot','Tester',1,2);


INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (1,'blender',29.99,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (1,'toaster',19.99,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (3,'lamp',5,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (6,'winter tires',200,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (5,'dresser',50,'anne');
